@server = https://scaling-disco-9vgv45gr6qph9pv4-8080.app.github.dev
###
GET {{server}}/api/idiomas/2
###
POST {{server}}/api/idiomas
Content-Type: application/json

{"nombre": "arabe", "estado": "extinto", "descripcion": "Como una flauta"}
###
GET {{server}}/api/generos
###
POST {{server}}/api/generos
Content-Type: application/json

{"nombre": "Joaquín"}


###
GET {{server}}/api/editoriales

###
GET {{server}}/api/editoriales/1
###
GET {{server}}/api/editoriales/1/formacion
###
GET {{server}}/api/libros



